server:
  port: 8900
eureka:
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://root:booszy@localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}
    appname: springcloud-turbine-dashboard
turbine:
  aggregator:
    clusterConfig: default
  #appConfig 后面是要检测的注册在eureka上的服务名，必须要有
  appConfig: springcloud-consumer-config,springcloud-provider-config,springcloud-zuul
  clusterNameExpression: "'default'"
spring:
  application:
    name: springcloud-turbine-dashboard